name: Postman

# TODO: Limit this to tags (?)
on: push

jobs:
  postman:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install openapi-to-postmanv2 (v4)
        run: npm i -g openapi-to-postmanv2@4
      - name: Convert .yaml files into Postman collections
        run: |
          mkdir -p postman

          for filename in *.yaml; do
            # https://github.com/postmanlabs/openapi-to-postman#-command-line-interface
            # %.* is used to strip the file extension
            openapi2postmanv2 -s "${filename}" -o "postman/${filename%.*}.json" --pretty --options folderStrategy=Tags
          done
