name: Tests

on: push

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Pytest
        # TODO: Run all tests on stage.seatable.io? Or test_teams.py on seatable-demo.de?
        run: pytest test_base_operations.py --color=yes
        env:
          SEATABLE_USERNAME: 'hulk'
          SEATABLE_PASSWORD: ${{ secrets.SEATABLE_PASSWORD }}
          SEATABLE_ADMIN_USERNAME: 'admin@seatable.io'
          SEATABLE_ADMIN_PASSWORD: ${{ secrets.SEATABLE_ADMIN_PASSWORD }}
